FROM debian:bullseye-slim
MAINTAINER Steven Saus (steven@faithcollapsing.com)

ENV DEBIAN_FRONTEND noninteractive
#https://github.com/badaix/snapcast
# Install packages
RUN apt-get update -y && \
    apt-get install -y curl \
    wget \
    mpd \
    mpc \
    detox \
    coreutils \
    grep \
    mp3info \
    exiftool \
    bc \
    unzip && \
    apt clean && \
    apt autoremove && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /run/php/ && mkdir -p /etc/apache2/{conf-available,mods-available}
COPY build/conf-available/ /etc/apache2/conf-available
COPY build/mods-available/ /etc/apache2/mods-available

EXPOSE 80
EXPOSE 8000
EXPOSE 6600
EXPOSE 8200
EXPOSE 1704
EXPOSE 1705
EXPOSE 1780
EXPOSE 5353

COPY build/run-httpd /usr/local/bin/
RUN chmod 755 /usr/local/bin/run-httpd

CMD ["/usr/local/bin/run-httpd"]
