version: "3.9"

services:
  mpd_streaming:
    image: local/docker_mpd_streaming
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mpd_streaming
    ports:
      - "8880:80"    # web
      - "8881:8000"  # stream - if you have something else using 8000, for example
      - "8882:6600"  # mpd control - if you have another MPD locally
      #- "8200:8200"  # minidlna
      #- "5353:5353"  # avahi? Not sure if dbus mount is enough
    restart: unless-stopped
    volumes:
      - ./snapserver_fifo:/tmp/snapfifo #for snapclient
      - ./music:/media/music/:ro  # your music, edit this.
      - ./playlists:/media/playlists/  # your playlists
      # - ./www:/var/www/  # for rompr; leave this, it will be auto-installed.
      - ./config/apache-sites/:/etc/apache2/sites-available/:ro # these will copy configs on startup
      - ./config:/media/config/:ro # these will copy configs on startup
      - /var/run/dbus:/var/run/dbus # for avahi to work  
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket # for avahi to work 
  snapclient:
    image: local/docker_mpd_snapserver
    build:
      context: .
      dockerfile: ./Dockerfile_snapserver
    container_name: mpd_snapserver
    ports:
      - "1704:1704"  #snapserver
      - "1705:1705"  #snapserver
      - "1780:1780"  #snapserver
    restart: unless-stopped
    volumes:
      - ./snapserver_fifo:/tmp/snapfifo #for snapclient
      - ./config:/media/config/:ro # these will copy configs on startup
      - /var/run/dbus:/var/run/dbus # for avahi to work  
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket # for avahi to work 
    depends_on:
      - mpd_streaming
