FROM debian:bullseye-slim
MAINTAINER Steven Saus (steven@faithcollapsing.com)

ENV DEBIAN_FRONTEND noninteractive
#https://github.com/badaix/snapcast
# Install packages
RUN apt-get update -y && \
    apt-get install -y curl \
    snapserver && \
    apt clean && \
    apt autoremove && \
    rm -rf /var/lib/apt/lists/*
EXPOSE 1704
EXPOSE 1705
EXPOSE 1780

COPY build/run-snapserver /usr/local/bin/
RUN chmod 755 /usr/local/bin/run-snapserver

CMD ["/usr/local/bin/run-snapserver"]

# This pulls in avahi on its own...
