version: "3.9"

services:
  apache:
    image: local/apache2_php7.4
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: apache
    ports:
    # web
      - "8180:80"
      # stream
      - ":8000"
      # mpd control
      - ":6600"
      # minidlna
      - ":8200"
      #snapserver
      - ":1704"
      - ":1705"
      - ":1780"
      # avahi? Not sure if dbus mount is enough
      - ":5353"

    restart: always
    volumes:
# straight up mounts
      - ./www:/var/www/
      - ./music:/media/music/
      - ./playlists:/media/playlists/
# these will copy configs on startup
      - ./config/apache-sites/:/etc/apache2/sites-available/
      - ./config:/media/config/
# for avahi    
      - /var/run/dbus:/var/run/dbus 
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
