#!/bin/sh
#rm /var/run/nginx.pid
set -e

# remove all sites enabled
rm -rf /etc/apache2/sites-enabled/*
# symlink everything in sites available
sites=$(ls -A "/etc/apache2/sites-available")
for site in $sites;do
    a2ensite ${site%.*}
done

# This should be triggered at runtime, perhaps?
#Environment variables to configure php
if [ ! -f /etc/php/7.4/myinit ];then 
    sed -ri -e  's/^allow_url_fopen =.*/allow_url_fopen = On/g' /etc/php/7.4/fpm/php.ini
    sed -ri -e  's/^memory_limit =.*/memory_limit = 512M/g' /etc/php/7.4/fpm/php.ini
    sed -ri -e  's/^max_execution_time =.*/max_execution_time = 1800/g' /etc/php/7.4/fpm/php.ini
    sed -ri -e  's/^post_max_size =.*/post_max_size = 256M/g' /etc/php/7.4/fpm/php.ini
    sed -ri -e  's/^upload_max_filesize =.*/upload_max_filesize = 8M/g' /etc/php/7.4/fpm/php.ini
    sed -ri -e  's/^max_file_uploads =.*/max_file_uploads = 50/g' /etc/php/7.4/fpm/php.ini
    sed -ri -e  's/^display_errors =.*/display_errors = On/g' /etc/php/7.4/fpm/php.ini
    sed -ri -e  's/^display_startup_errors =.*/display_startup_errors = On/g' /etc/php/7.4/fpm/php.ini
    touch /etc/php/7.4/myinit
fi
# RUN echo "<?php phpinfo(); ?>" > /app/rompr/phpinfo.php
update-rc.d php7.4-fpm defaults
a2enmod proxy_fcgi setenvif
a2enconf php7.4-fpm

/etc/init.d/php7.4-fpm restart
# /usr/sbin/apachectl start
#/etc/init.d/apache2 start
apachectl -D FOREGROUND
#exec /usr/sbin/nginx -g 'daemon off;'
